// <auto-generated />
using AnimalsAPI.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalsAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190724141623_TestSeedData")]
    partial class TestSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnimalsAPI.Domain.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("YearOfBirth");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amber",
                            Type = "Bengal",
                            YearOfBirth = 2000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tiddles",
                            Type = "Tabby",
                            YearOfBirth = 2010
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mr Mestopheles",
                            Type = "Ginger tom",
                            YearOfBirth = 2001
                        },
                        new
                        {
                            Id = 4,
                            Name = "Spot",
                            Type = "Old moggy",
                            YearOfBirth = 2012
                        });
                });

            modelBuilder.Entity("AnimalsAPI.Domain.Models.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Name = "Squealer"
                        },
                        new
                        {
                            Id = 2,
                            Age = 1,
                            Name = "Squidgy"
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            Name = "Fluff Bag"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
